- name: Update software
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes
    autoremove: yes

- name: Check if reboot is required
  stat: 
    path: /var/run/reboot-required
  register: reboot_file

- name: Reboot required?
  when: reboot_file.stat.exists
  command: /bin/true
  notify: "server reboot"

- name: Ensure the 'pi' user is absent
  user:
    name: pi
    state: absent
    remove: yes
  notify: "server reboot"

- name: Ensure the hostname is set correctly
  hostname:
    name: "{{ inventory_hostname }}"

- name: Ensure Timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"

- name: Ensure UFW installed and present
  apt:
    name: ufw
    state: present

- name: Configure ufw to be enabled and allow SSH
  ufw:
    state: enabled
    rule: allow
    name: OpenSSH

- name: Disable SSH Password logins
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: restart ssh

- name: Set static IP address
  when: static_ip is defined
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
        interface {{ static_ip.interface }}
        static ip_address={{ static_ip.ip_addr }}/24
        static routers={{ static_ip.router }}
        static domain_name_servers={{ static_ip.router }}
        static domain_search={{ static_ip.domain }}
  notify: "server reboot"

# Stop HDMI service based on these instructions: 
#Â https://frederik.lindenaar.nl/2018/05/11/raspberry-pi-power-saving-disable-hdmi-port-and-others-the-systemd-way.html

- name: Install setting to stop HDMI on headless servers
  when: pi_headless is defined and pi_headless
  template:
    src: rpi_no_hdmi.j2
    dest: /etc/systemd/system/rpi_no_hdmi.service

- name: Start the stop HDMI  service
  when: pi_headless is defined and pi_headless
  systemd:
    daemon_reload: yes
    name: rpi_no_hdmi.service
    state: started
    enabled: yes
